server:
  port: 9002
  servlet:
    context-path: /thirdParty
spring:
  application:
    name: openThirdParty
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  #  显示SQL日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper的xml文件
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    root : INFO